language: node_js
node_js:
- '5'
- '6'
notifications:
  slack:
    rooms:
      secure: VuXD8jH6FWZaWfJK3ll98cCDIvi4lVINBFK50W/9Cg6ut6rSxYyCv0SVRYK3iTTR9ohFFHPAgUgYSB8uD8cTj8Ezq2TYxAM3tUCK/lJB+BmWM536gFDGzDhHDyoG6zfc5ZPvN4+iZ5QD5aSKz2szo9D7vMgGK/pSHnt9uLt/n1mMa7prWL6YcS/LRYDaMP53f9jWcf8AIqkgoFrO+dJF3fa9YhgC9p+oUSEOnl7uDx4UCYrNVCot174+D8EymQFk209Fh4OxDW3CF1YEbSc2G3s7GW/r1YSeNHJLPDwFME6/73SjmD4wVSW573B7MfTkDAIN8uosziRVTxX7FaxOvpw8GFpyvNhuIf4fJlj4XecZi6im1daYsH+Tr23QdHupwQyND2iK/N17UrW/hxz+/w+WIFbhzzTACLcPk2pmO71QN4JOV/R088NoQ9u8w9ywT7yu2nru0D4ijXzcSoCZG0ZOeQD7piRkdWj+Ec4ku1INqistPThwlrNt576jj4pDvddCScpt3jrdiuArey3EaeQSv1gC3Z/qG4Tjt4HDsfU9O5P1eDon41lruGxqcpKXp6ykrhBoBv4JCjhtIn6K6zw9iyA5Au297aUCkf0z3wba3ybPxLbDPwj6f7/gPIP4FeFD8g1xZVK7TXaReB2ya8G9PCwWvnjy+lMprYXpZ+k=
